### ISSUE TITLE
No such export GetQueueExports in resource connectqueue

### ISSUE THREAD

**Issue by crispyaus** [Nick78111/ConnectQueue#13]
Hello, I've had this issue for some weeks now, when the server starts it will say this:

`SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:924: No such export GetQueueExports in resource connectqueue`

I've deleted cache & reinstalled to no luck. Please Help 👍

**Comment by alex070609** [comment]
same here

**Comment by alex070609** [comment]
Found it ! just rename ConnectQueue to connectqueue (replace the 'C' and 'Q' in uppercase to 'c' and 'q' in lowercase) 😄
