### ISSUE TITLE
Error whe i use Queue.Exports.SetPos()

### ISSUE THREAD

**Issue by djmetla** [Nick78111/ConnectQueue#14]
![Screenshot_6](https://user-images.githubusercontent.com/2371031/78304030-28bb3100-753e-11ea-84a1-259210917ca8.png)

Hey, man! I try create Command for admins /priority STEAMID POSITION for manual priority in Queue. I using Queue.Exports:SetPos('steam:xxxxxxxx', position[int]) and i obtain this error. Can you help me ?

Ty a lot this addon is a TOP!

**Comment by Nick78111** [comment]
This function requires a table of id(s) not a string.
