### ISSUE TITLE
Queue Freezes all.

### ISSUE THREAD

**Issue by JaroSound** [Nick78111/ConnectQueue#3]
Sometimes there is 26/32 player and queue stop moving.

I have sometimes 100ppls in queue :(

**Comment by Nick78111** [comment]
I'll have an update on here soon, just need to test it on a server. Hopefully should fix some of the freezing issues.

**Comment by ccrumbb** [comment]
Hello @Nick78111, any update for that?
Anyway, good job with script.

**Comment by Nick78111** [comment]
I still need to test it with a full server and change a few things, shouldn't be too much longer.

**Comment by Nardah** [comment]
@Nick78111 Do you need a server to test it for you?

**Comment by timnboys** [comment]
@Nick78111 did you find a fix for the freezing issue? as I am interested on how to fix the freezing issue myself.

**Comment by smishcraft** [comment]
Same issue here, Players get stuck in the queue when 20 people are already loaded into the server.

**Comment by ccrumbb** [comment]
Guys, I'm affraid it's FiveM issue. I implemented my own que system and it's behave in the same way if there is many connection to the server.
