### ISSUE TITLE
sh_queue.lua:382 Exports()

### ISSUE THREAD

**Issue by TweathX** [Nick78111/ConnectQueue#8]
So apparently I'm having a error with the global exports() on line 382.

`lua
Error loading script shared/sh_queue.lua in resource connectqueue: shared/sh_queue.lua:382: attempt to call a table value (global 'exports')
stack traceback:
        shared/sh_queue.lua:382: in main chunk
Failed to load script shared/sh_queue.lua.x
`

Line 382

`lua
exports("Exports", function()
    return Queue
end)`

**Comment by Nick78111** [comment]
Do you have the latest fxserver build?
